global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'rice_model_monitoring'
    static_configs:
      - targets: ['192.168.1.8:5000']  # GANTI DENGAN IP ADDRESS DAN PORT MLflow Tracking Server ANDA