name: CI Advanced (Docker Push)

on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4

      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dan Kirim ke Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: Workflow-CI
          file: Workflow-CI/Dockerfile
          push: true
          # GANTI 'febrian220205' DENGAN USERNAME DOCKER HUB ANDA:
          tags: febrian220205/rice-classification-project:latest