name: Data Preprocessing Workflow

# Trigger: Workflow jalan setiap ada push ke repository
on: [push]

jobs:
  build-and-process:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode dari repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Siapkan Python
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # 3. Install library dari requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Jalankan script preprocessing
    - name: Run Preprocessing Script
      run: python preprocessing/automate_NamaAnda.py

    # 5. Upload hasil preprocessing sebagai Artifact (Syarat "mengembalikan dataset")
    - name: Upload Processed Dataset
      uses: actions/upload-artifact@v4
      with:
        name: processed-dataset
        path: rice_processed.csv
        retention-days: 1